### ISSUE TITLE
Meeting Transcription Service

### ISSUE THREAD

**Issue by Space-Turtle0** [School-Simplified/Timmy-SchoolSimplified#136]

**Comment by Puncher1** [comment]
# Meeting Transcriber | Speech to Text

-> Essentially have a user invoke `+recmeeting`
> From there, we have Timmy join and start recording the voice channel. (This part is really easy since it's all handled by PyCord). Once they invoke the same command again, it should stop recording, upload the MP4 to a Google Storage bucket, then have google start transcribing that MP4. Once that's finished, use a for loop to get it all in a list. Make sure you handle collecting different speakers and bundling them together. 

>Then using all this information, we paste it in a google doc.

>This is the google doc process:
First we make a copy of a template (for design purposes), then we dump all the list data (transcription) in there, and then share the doc with the user's email. 

<ins>Most of this is basically done in the file I replied to</ins>, just needs some fine-tweaking and stuff. Since that audio bug hasn't been fixed yet on PyCord, we can't really test recording from a vc. So use [this MP3](https://cdn.discordapp.com/attachments/932066545738350640/939591665973346414/ttsMP3.com_VoiceText_2022-2-5_13_41_34.mp3) 
whatever other file that has multiple voices so we can test the api in differentiating speakers

**For code, creds and tokens contact SpaceTurtle#2587 or Puncher#1111 on discord**

**Comment by Space-Turtle0** [comment]
No longer required since we're moving to Google Meet
