### ISSUE TITLE
Voting Bot

### ISSUE THREAD

**Issue by Space-Turtle0** [School-Simplified/Timmy-SchoolSimplified#146]
**Project Title**
Voting Bot

**Team Requester**
To be used across all of School Simplified

**Project Description**
Allows people to vote on topics anonymously. Can be via reaction roles or a popup idrc just make it easy.

Requested by @Ethan-Hsu

**Comment by pandabear189** [comment]
since they want it to be anonymous, maybe we should want until buttons and dropdown menus are added to forms so we could have a user click a button which would open the form with buttons to vote.
Currently, the best alternative would be sending an ephemeral message with buttons/dropdown for the user to vote

**Comment by pandabear189** [comment]
#189
